# Generated by Django 4.2.5 on 2024-05-17 16:46

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userevent',
            name='color',
            field=models.CharField(default='#000000', max_length=7, validators=[events.models.color_validator]),
        ),
    ]
