# Generated by Django 4.2.5 on 2024-05-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_userevent_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userevent',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
