# Generated by Django 4.2.5 on 2024-05-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_userevent_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='userevent',
            name='start_notified',
            field=models.BooleanField(default=False),
        ),
    ]
