# Generated by Django 4.2.5 on 2023-10-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short_description',
            field=models.TextField(default='blablabla'),
            preserve_default=False,
        ),
    ]
