# Generated by Django 4.2.5 on 2024-02-02 10:25

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_post_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='preview_image',
            field=models.ImageField(default=pathlib.PureWindowsPath('C:/Users/serje/WebstormProjects/uits/backend/photos/default.jpg'), upload_to='photos/%Y/%m/%d', verbose_name='Превью фото'),
        ),
    ]
