# Generated by Django 4.2.5 on 2024-02-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_post_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='short_description',
            field=models.TextField(max_length=280),
        ),
    ]
