# Generated by Django 4.2.5 on 2024-02-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_alter_post_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='preview_image_description',
            field=models.TextField(default='', max_length=256),
        ),
    ]
