# Generated by Django 4.2.5 on 2024-02-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='preview_image_description',
            field=models.CharField(default='', max_length=256),
        ),
    ]
