# Generated by Django 4.2.5 on 2024-02-24 12:12

from django.db import migrations
import imagekit.models.fields
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_alter_post_preview_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='preview_image',
            field=imagekit.models.fields.ProcessedImageField(default=pathlib.PureWindowsPath('C:/Users/serje/WebstormProjects/uits/backend/photos/default.jpg'), upload_to='photos/%Y/%m/%d', verbose_name='Превью фото'),
        ),
    ]
