# Generated by Django 4.2.5 on 2024-02-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('NEWS', 'News'), ('ANNOUNCEMENT', 'Announcement')], default='NEWS', max_length=12),
        ),
    ]
