# Generated by Django 4.2.5 on 2024-04-06 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0016_post_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=django_quill.fields.QuillField(verbose_name='Содержание статьи'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('NEWS', 'News'), ('ANNOUNCEMENT', 'Announcement')], default='NEWS', max_length=12, verbose_name='Тип поста'),
        ),
        migrations.AlterField(
            model_name='post',
            name='preview_image_description',
            field=models.CharField(default='', max_length=256, verbose_name='Краткое описание фотографии'),
        ),
        migrations.AlterField(
            model_name='post',
            name='short_description',
            field=models.TextField(max_length=280, verbose_name='Краткое описание'),
        ),
    ]
