# Generated by Django 4.2.5 on 2024-05-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_alter_post_author_alter_post_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='display',
            field=models.BooleanField(default=True, verbose_name='Отображать?'),
        ),
    ]
