# Generated by Django 4.2.5 on 2024-09-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_alter_post_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('NEW', 'News'), ('ANNOUNCEMENT', 'Announcement')], default='NEW', max_length=12, verbose_name='Тип поста'),
        ),
    ]
