# Generated by Django 4.2.5 on 2024-09-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0019_alter_post_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('NEWS', 'News'), ('ANNOUNCEMENT', 'Announcement')], default='NEWS', max_length=12, verbose_name='Тип поста'),
        ),
    ]
