# Generated by Django 4.2.5 on 2024-05-08 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editable_pages', '0002_alter_editablepage_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editablepage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='editablepage',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='editablepage',
            name='page',
            field=models.CharField(max_length=100, unique=True, verbose_name='Идентификатор страницы'),
        ),
        migrations.AlterField(
            model_name='editablepage',
            name='text',
            field=models.TextField(verbose_name='Контент Markdown'),
        ),
    ]
