# Generated by Django 4.2.5 on 2024-05-08 22:01

from django.db import migrations

from uits.settings import DEFAULT_EDITABLE_PAGES

default_pages_name = DEFAULT_EDITABLE_PAGES

def add_default_editable_pages(apps, schema_editor):
    EditablePage = apps.get_model('editable_pages', 'EditablePage')
    default_pages = []
    for page_name in default_pages_name:
        default_pages.append(EditablePage(text="Пусто", page=page_name))

    EditablePage.objects.bulk_create(default_pages, ignore_conflicts=True)


def noop(apps, schema_editor):
    pass
    # print('WARNING noop operation for 0003_alter_editablepage_created_at_and_more')
    # print('Next try to migrate 0003_alter_editablepage_created_at_and_more should be error')
    # print('You can skip this migration')



class Migration(migrations.Migration):

    dependencies = [
        ('editable_pages', '0004_alter_editablepage_options_alter_editablepage_page'),
    ]

    operations = [
        migrations.RunPython(add_default_editable_pages, noop, atomic=True)
    ]
