# Generated by Django 4.2.5 on 2024-05-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editable_pages', '0006_update_default_editable_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editablepage',
            name='text',
            field=models.TextField(blank=True, verbose_name='Контент Markdown'),
        ),
    ]
