# Generated by Django 4.2.5 on 2024-10-24 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0012_rename_messanger_teacher_messenger_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование дисциплины')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание дисциплины')),
            ],
        )
    ]
