# Generated by Django 4.2.5 on 2024-10-24 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'учебная дисциплина', 'verbose_name_plural': 'учебные дисциплины'},
        ),
    ]
