# Generated by Django 4.2.5 on 2023-09-26 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_rename_lastname_employee_last_name_employee_bio_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Teacher',
        ),
    ]
