# Generated by Django 4.2.5 on 2024-04-06 15:11

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_teacher_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default=None, null=True, upload_to='avatars/%Y/%m/%d'),
        ),
    ]
