# Generated by Django 4.2.5 on 2024-05-07 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_helpersemployee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='helpersemployee',
            options={'verbose_name': 'персонал', 'verbose_name_plural': 'учебно-вспомогательный персонал'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'преподаватель', 'verbose_name_plural': 'преподаватели'},
        ),
    ]
