# Generated by Django 4.2.5 on 2024-05-20 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_alter_helpersemployee_options_alter_teacher_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Биография'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='degree',
            field=models.CharField(blank=True, choices=[('Доктор технических наук', 'Doctor Tech'), ('Кандидат технических наук', 'Candidate Tech'), ('Кандидат педагогических наук', 'Candidate Ped'), ('Доктор физико-математических наук', 'Doctor Phys Math'), ('Кандидат физико-математических наук', 'Candidate Phys Math'), ('Доктор экономических наук', 'Doctor Econom'), ('Кандидат экономических наук', 'Candidate Econom')], max_length=100, null=True, verbose_name='Степень'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='patronymic',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='position',
            field=models.CharField(max_length=100, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='rank',
            field=models.CharField(blank=True, choices=[('Доцент', 'Reader'), ('Профессор', 'Professor')], max_length=100, null=True, verbose_name='Звание'),
        ),
    ]
