# Generated by Django 4.2.5 on 2024-05-20 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_alter_teacher_bio_alter_teacher_degree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='degree',
            field=models.CharField(blank=True, choices=[('DOCTOR_TECH', 'Доктор технических наук'), ('CANDIDATE_TECH', 'Кандидат технических наук'), ('CANDIDATE_PED', 'Кандидат педагогических наук'), ('DOCTOR_PHYS_MATH', 'Доктор физико-математических наук'), ('CANDIDATE_PHYS_MATH', 'Кандидат физико-математических наук'), ('DOCTOR_ECONOM', 'Доктор экономических наук'), ('CANDIDATE_ECONOM', 'Кандидат экономических наук')], max_length=100, null=True, verbose_name='Степень'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='rank',
            field=models.CharField(blank=True, choices=[('READER', 'Доцент'), ('PROFESSOR', 'Профессор')], max_length=100, null=True, verbose_name='Звание'),
        ),
    ]
