# Generated by Django 4.2.5 on 2024-10-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_teacher_email_teacher_experience_teacher_messanger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='education',
            field=models.TextField(blank=True, null=True, verbose_name='Образование'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='qualification',
            field=models.TextField(blank=True, null=True, verbose_name='Повышение квалификации'),
        ),
    ]
