# Generated by Django 4.2.5 on 2024-09-29 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_alter_teacher_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='teacher',
        ),
    ]
