# Generated by Django 4.2.5 on 2024-10-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0002_alter_subject_options'),
        ('employee', '0012_rename_messanger_teacher_messenger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(related_name='subjects', to='subject.subject'),
        ),
    ]
