# Generated by Django 4.2.5 on 2024-09-29 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_remove_teacher_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='user_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
