# Generated by Django 4.2.5 on 2024-04-17 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0005_teacher_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='employee.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleClassTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_number', models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fourth'), (5, 'Fifth'), (6, 'Sixth'), (7, 'Seventh'), (8, 'Eighth')])),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=256)),
                ('type', models.CharField(max_length=128)),
                ('cabinet', models.CharField(blank=True, max_length=128, null=True)),
                ('subgroup', models.CharField(blank=True, max_length=128, null=True)),
                ('class_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='schedule.scheduleclasstime')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleLessonDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.CharField(max_length=50)),
                ('end_date', models.CharField(blank=True, max_length=50, null=True)),
                ('is_period', models.BooleanField(default=False)),
                ('alternatively_period', models.BooleanField(default=False)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='schedule.schedulelesson')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')])),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='schedule.schedule')),
            ],
        ),
        migrations.AddField(
            model_name='scheduleclasstime',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_times', to='schedule.scheduleday'),
        ),
    ]
