# Generated by Django 4.2.5 on 2024-05-25 19:07

from django.db import migrations


def delete_all_schedules(apps, schema_editor):
    Schedule = apps.get_model('schedule', 'Schedule')
    Schedule.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(delete_all_schedules)
    ]
