# Generated by Django 4.2.5 on 2024-05-25 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_delete_all_schedules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleday',
            name='schedule',
        ),
        migrations.AddField(
            model_name='schedulelesson',
            name='schedule',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='schedule.schedule'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedulelesson',
            name='week_number',
            field=models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedulelesson',
            name='class_time',
            field=models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fourth'), (5, 'Fifth'), (6, 'Sixth'), (7, 'Seventh'), (8, 'Eighth')]),
        ),
        migrations.DeleteModel(
            name='ScheduleClassTime',
        ),
        migrations.DeleteModel(
            name='ScheduleDay',
        ),
    ]
