# Generated by Django 4.2.5 on 2024-05-25 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_alter_teacher_degree_alter_teacher_rank'),
        ('schedule', '0003_remove_scheduleday_schedule_schedulelesson_schedule_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'Расписание', 'verbose_name_plural': 'Расписания'},
        ),
        migrations.AlterModelOptions(
            name='schedulelessondate',
            options={'verbose_name': 'Дата пары', 'verbose_name_plural': 'Даты пар'},
        ),
        migrations.RemoveField(
            model_name='schedulelessondate',
            name='is_period',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='employee.teacher', verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='schedulelesson',
            name='cabinet',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Кабинет'),
        ),
        migrations.AlterField(
            model_name='schedulelesson',
            name='class_time',
            field=models.IntegerField(choices=[(1, '8:30 - 10:10'), (2, '10:20 - 12:00'), (3, '12:20 - 14:00'), (4, '14:10 - 15:50'), (5, '16:00 - 17:40'), (6, '18:00 - 19:30'), (7, '19:40 - 21:10'), (8, '21:20 - 22:50')], verbose_name='Пара'),
        ),
        migrations.AlterField(
            model_name='schedulelesson',
            name='group',
            field=models.CharField(max_length=128, verbose_name='Группы'),
        ),
        migrations.AlterField(
            model_name='schedulelesson',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Название предмета'),
        ),
        migrations.AlterField(
            model_name='schedulelesson',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='schedule.schedule', verbose_name='Расписание'),
        ),
        migrations.AlterField(
            model_name='schedulelesson',
            name='subgroup',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Подгруппа'),
        ),
        migrations.AlterField(
            model_name='schedulelesson',
            name='type',
            field=models.CharField(max_length=128, verbose_name='Тип пары'),
        ),
        migrations.AlterField(
            model_name='schedulelesson',
            name='week_number',
            field=models.IntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота')], verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='schedulelessondate',
            name='alternatively_period',
            field=models.BooleanField(default=False, help_text='Да - через неделю. Нет - каждая неделя', verbose_name='Через неделю?'),
        ),
        migrations.AlterField(
            model_name='schedulelessondate',
            name='end_date',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Дата конца (опционально)'),
        ),
        migrations.AlterField(
            model_name='schedulelessondate',
            name='start_date',
            field=models.CharField(help_text='Формат ввода: DD.MM - без года', max_length=5, verbose_name='Дата начала'),
        ),
    ]
