# Generated by Django 4.2.5 on 2024-05-25 22:58

import department.employee.schedule.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_alter_schedule_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedulelesson',
            options={'verbose_name': 'Пара', 'verbose_name_plural': 'Пары'},
        ),
        migrations.AddField(
            model_name='schedule',
            name='imported_file_name',
            field=models.CharField(blank=True, editable=False, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='schedulelesson',
            name='class_time',
            field=models.IntegerField(choices=[(1, '8:30 - 10:10'), (2, '10:20 - 12:00'), (3, '12:20 - 14:00'), (4, '14:10 - 15:50'), (5, '16:00 - 17:40'), (6, '18:00 - 19:30'), (7, '19:40 - 21:10'), (8, '21:20 - 22:50')], verbose_name='Время пары'),
        ),
        migrations.AlterField(
            model_name='schedulelesson',
            name='schedule',
            field=models.ForeignKey(help_text='Пара обязательно должна быть привязана к объекту расписания. Если нет объекта с нужным преподавателем, создайте нажал на зелёный плюс. Для одного преподавателя доступно только одно расписание', on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='schedule.schedule', verbose_name='Расписание'),
        ),
        migrations.AlterField(
            model_name='schedulelesson',
            name='type',
            field=models.CharField(help_text='Семинар, лекция, лабораторные занятия либо пользовательский тип', max_length=128, verbose_name='Тип пары'),
        ),
        migrations.AlterField(
            model_name='schedulelessondate',
            name='end_date',
            field=models.CharField(blank=True, max_length=5, null=True, validators=[department.employee.schedule.models.validate_lesson_date_format], verbose_name='Дата конца (опционально)'),
        ),
        migrations.AlterField(
            model_name='schedulelessondate',
            name='start_date',
            field=models.CharField(max_length=5, validators=[department.employee.schedule.models.validate_lesson_date_format], verbose_name='Дата начала'),
        ),
    ]
