# Generated by Django 4.2.5 on 2024-02-24 14:53

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_moderator'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(default='photos\\default.png', upload_to='photos/avatars/%Y/%m/%d', verbose_name='Аватар пользователя'),
            preserve_default=False,
        ),
    ]
