# Generated by Django 4.2.5 on 2024-02-24 15:06

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default=True, null=True, upload_to='photos/avatars/%Y/%m/%d', verbose_name='Аватар пользователя'),
        ),
    ]
