# Generated by Django 4.2.5 on 2024-05-12 16:16

from django.db import migrations, models
import tg_bot.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_code',
            field=models.CharField(default=tg_bot.utils.generate_telegram_code, editable=False, max_length=12),
        ),
    ]
