# Generated by Django 4.2.5 on 2024-05-12 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_code',
            field=models.CharField(default='default', editable=False, max_length=12),
        ),
    ]
