# Generated by Django 4.2.5 on 2024-05-12 16:17

from django.db import migrations, models
import tg_bot.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_telegram_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram_code',
            field=models.CharField(default=tg_bot.utils.generate_telegram_code, editable=False, max_length=12, unique=True),
        ),
    ]
