# Generated by Django 4.2.5 on 2024-05-12 22:10

from django.db import migrations

from tg_bot.utils import generate_telegram_code


def assign_telegram_code_to_all(apps, schema_editor):
    User = apps.get_model('users', 'User')

    for user in User.objects.all():
        user.telegram_code = generate_telegram_code()
        user.save()


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0006_user_telegram_code'),
    ]

    operations = [
        migrations.RunPython(assign_telegram_code_to_all, lambda a, s: None, atomic=True)
    ]
