# Generated by Django 4.2.5 on 2024-05-12 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_assign_telegram_code_to_all'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram_code',
            field=models.CharField(default=None, editable=False, max_length=12, unique=True),
        ),
    ]
