# Generated by Django 4.2.5 on 2024-05-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_is_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_moderator',
            field=models.BooleanField(default=False, help_text='Указывает, что пользователь имеет права модератора.', verbose_name='Статус модератора'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_teacher',
            field=models.BooleanField(default=False, help_text='Указывает, что пользователь имеет права преподавателя.', verbose_name='Статус преподавателя'),
        ),
    ]
