# Generated by Django 4.2.5 on 2024-10-13 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('achievements', '0002_alter_achievement_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='linked_to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievements', to=settings.AUTH_USER_MODEL, verbose_name='Привязан к'),
        ),
    ]
