# Generated by Django 4.2.5 on 2024-10-13 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_alter_teacher_degree_alter_teacher_rank'),
        ('achievements', '0003_achievement_is_published_achievement_linked_to_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='author',
        ),
        migrations.AlterField(
            model_name='achievement',
            name='linked_to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievements', to='employee.teacher', verbose_name='Привязан к'),
        ),
    ]
