# Generated by Django 4.2.5 on 2024-10-13 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0004_remove_achievement_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievement',
            old_name='linked_to_user',
            new_name='teacher',
        ),
    ]
