# Generated by Django 4.2.5 on 2024-10-13 17:07

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0005_rename_linked_to_user_achievement_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(default=1, upload_to='photos/%Y/%m/%d', verbose_name='Превью фото'),
            preserve_default=False,
        ),
    ]
