# Generated by Django 4.2.5 on 2024-05-12 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tg_bot', '0002_telegramuser_chat_id_alter_telegramuser_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='assigned_user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
